# logfilename                                        [owner:group]      mode  count  size(KB)  when  flags
/Users/ifthenvoid/.robin/logs/gateway.log            ifthenvoid:staff   640   7      10240     *     NJ
/Users/ifthenvoid/.robin/logs/gateway.error.log      ifthenvoid:staff   640   7      10240     *     NJ
/Users/ifthenvoid/.robin/logs/agent.log              ifthenvoid:staff   640   7      10240     *     NJ
/Users/ifthenvoid/.robin/logs/errors.log             ifthenvoid:staff   640   5      5120      *     NJ
/Users/ifthenvoid/.robin/logs/router.jsonl           ifthenvoid:staff   640   7      10240     *     NJ
